onlyBuiltDependencies:
  - esbuild
  - fsevents

overrides:
  '@ensdomains/address-encoder': 1.1.4
  '@ensdomains/content-hash': 3.1.1
  '@nomiclabs/hardhat-ethers': npm:hardhat-deploy-ethers@0.3.0-beta.13
  '@wagmi/core': 2.13.3
  '@walletconnect/ethereum-provider': 2.11.1
  '@walletconnect/modal': 2.6.2
  aggregate-error: npm:@socketregistry/aggregate-error@^1
  array-buffer-byte-length: npm:@socketregistry/array-buffer-byte-length@^1
  array-flatten: npm:@socketregistry/array-flatten@^1
  array-includes: npm:@socketregistry/array-includes@^1
  array.prototype.findlast: npm:@socketregistry/array.prototype.findlast@^1
  array.prototype.findlastindex: npm:@socketregistry/array.prototype.findlastindex@^1
  array.prototype.flat: npm:@socketregistry/array.prototype.flat@^1
  array.prototype.flatmap: npm:@socketregistry/array.prototype.flatmap@^1
  array.prototype.toreversed: npm:@socketregistry/array.prototype.toreversed@^1
  array.prototype.tosorted: npm:@socketregistry/array.prototype.tosorted@^1
  arraybuffer.prototype.slice: npm:@socketregistry/arraybuffer.prototype.slice@^1
  available-typed-arrays: npm:@socketregistry/available-typed-arrays@^1
  bn.js: npm:bn.js@^5.2.0
  clones-with-immutable-args: npm:empty-npm-package@*
  deep-equal: npm:@socketregistry/deep-equal@^1
  define-properties: npm:@socketregistry/define-properties@^1
  es-define-property: npm:@socketregistry/es-define-property@^1
  es-get-iterator: npm:@socketregistry/es-get-iterator@^1
  es-iterator-helpers: npm:@socketregistry/es-iterator-helpers@^1
  es-set-tostringtag: npm:@socketregistry/es-set-tostringtag@^1
  es6-symbol: npm:@socketregistry/es6-symbol@^1
  for-each: npm:@socketregistry/for-each@^1
  function-bind: npm:@socketregistry/function-bind@^1
  function.prototype.name: npm:@socketregistry/function.prototype.name@^1
  functions-have-names: npm:@socketregistry/functions-have-names@^1
  get-symbol-description: npm:@socketregistry/get-symbol-description@^1
  globalthis: npm:@socketregistry/globalthis@^1
  gopd: npm:@socketregistry/gopd@^1
  has-property-descriptors: npm:@socketregistry/has-property-descriptors@^1
  has-proto: npm:@socketregistry/has-proto@^1
  has-symbols: npm:@socketregistry/has-symbols@^1
  has-tostringtag: npm:@socketregistry/has-tostringtag@^1
  hasown: npm:@socketregistry/hasown@^1
  indent-string: npm:@socketregistry/indent-string@^1
  internal-slot: npm:@socketregistry/internal-slot@^1
  is-arguments: npm:@socketregistry/is-arguments@^1
  is-array-buffer: npm:@socketregistry/is-array-buffer@^1
  is-bigint: npm:@socketregistry/is-bigint@^1
  is-boolean-object: npm:@socketregistry/is-boolean-object@^1
  is-core-module: npm:@socketregistry/is-core-module@^1
  is-date-object: npm:@socketregistry/is-date-object@^1
  is-generator-function: npm:@socketregistry/is-generator-function@^1
  is-interactive: npm:@socketregistry/is-interactive@^1
  is-map: npm:@socketregistry/is-map@^1
  is-negative-zero: npm:@socketregistry/is-negative-zero@^1
  is-number-object: npm:@socketregistry/is-number-object@^1
  is-regex: npm:@socketregistry/is-regex@^1
  is-set: npm:@socketregistry/is-set@^1
  is-shared-array-buffer: npm:@socketregistry/is-shared-array-buffer@^1
  is-string: npm:@socketregistry/is-string@^1
  is-symbol: npm:@socketregistry/is-symbol@^1
  is-typed-array: npm:@socketregistry/is-typed-array@^1
  is-unicode-supported: npm:@socketregistry/is-unicode-supported@^1
  is-weakmap: npm:@socketregistry/is-weakmap@^1
  is-weakref: npm:@socketregistry/is-weakref@^1
  is-weakset: npm:@socketregistry/is-weakset@^1
  isarray: npm:@socketregistry/isarray@^1
  iterator.prototype: npm:@socketregistry/iterator.prototype@^1
  number-is-nan: npm:@socketregistry/number-is-nan@^1
  object-assign: npm:@socketregistry/object-assign@^1
  object-is: npm:@socketregistry/object-is@^1
  object-keys: npm:@socketregistry/object-keys@^1
  object.assign: npm:@socketregistry/object.assign@^1
  object.entries: npm:@socketregistry/object.entries@^1
  object.fromentries: npm:@socketregistry/object.fromentries@^1
  object.groupby: npm:@socketregistry/object.groupby@^1
  object.hasown: npm:@socketregistry/object.hasown@^1
  object.values: npm:@socketregistry/object.values@^1
  path-parse: npm:@socketregistry/path-parse@^1
  querystringify: npm:@socketregistry/querystringify@^1
  react: ^18.2.0
  react-dom: ^18.2.0
  reflect.getprototypeof: npm:@socketregistry/reflect.getprototypeof@^1
  regexp.prototype.flags: npm:@socketregistry/regexp.prototype.flags@^1
  safe-array-concat: npm:@socketregistry/safe-array-concat@^1
  safe-buffer: npm:@socketregistry/safe-buffer@^1
  safe-regex-test: npm:@socketregistry/safe-regex-test@^1
  safer-buffer: npm:@socketregistry/safer-buffer@^1
  set-function-length: npm:@socketregistry/set-function-length@^1
  shell-quote: npm:shell-quote@^1
  side-channel: npm:@socketregistry/side-channel@^1
  string.prototype.matchall: npm:@socketregistry/string.prototype.matchall@^1
  string.prototype.trim: npm:@socketregistry/string.prototype.trim@^1
  string.prototype.trimend: npm:@socketregistry/string.prototype.trimend@^1
  string.prototype.trimstart: npm:@socketregistry/string.prototype.trimstart@^1
  typed-array-buffer: npm:@socketregistry/typed-array-buffer@^1
  typed-array-byte-length: npm:@socketregistry/typed-array-byte-length@^1
  typed-array-byte-offset: npm:@socketregistry/typed-array-byte-offset@^1
  typed-array-length: npm:@socketregistry/typed-array-length@^1
  unbox-primitive: npm:@socketregistry/unbox-primitive@^1
  which-boxed-primitive: npm:@socketregistry/which-boxed-primitive@^1
  which-collection: npm:@socketregistry/which-collection@^1
  which-typed-array: npm:@socketregistry/which-typed-array@^1
  wrtc: https://registry.npmjs.org/@koush/wrtc/-/wrtc-0.5.2.tgz

patchedDependencies:
  '@ensdomains/dnsprovejs@0.5.1': patches/@ensdomains__dnsprovejs@0.5.1.patch
  '@ensdomains/ens-contracts@1.6.0': patches/@ensdomains__ens-contracts@1.6.0.patch
  '@ensdomains/ens-test-env@1.0.1': patches/@ensdomains__ens-test-env@1.0.1.patch
  '@ensdomains/ensjs': patches/@ensdomains__ensjs.patch
  '@ensdomains/thorin': patches/@ensdomains__thorin.patch
  '@nomicfoundation/hardhat-viem@2.0.3': patches/@nomicfoundation%2Fhardhat-viem@2.0.3.patch
  hardhat-deploy@0.12.4: patches/hardhat-deploy@0.12.4.patch
  next-dev-https@0.1.2: patches/next-dev-https@0.1.2.patch
  node-forge@1.3.1: patches/node-forge@1.3.1.patch
  react-confetti@6.1.0: patches/react-confetti@6.1.0.patch
  viem@2.19.4: patches/viem@2.19.4.patch
